name: abus_example
description: Example app demonstrating usage of the abus package.
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  abus:
    path: ../
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
